kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s_deployment.yml
    kompose.image-pull-policy: Never
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: order
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o k8s_deployment.yml
        kompose.image-pull-policy: Never
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/ecommerce-microservices-default: "true"
        io.kompose.service: order
    spec:
      containers:
        - envFrom:
           - configMapRef:
              name: order-config
           - secretRef:
              name: order-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          image: dheerukiregistry.azurecr.io/ecommerce-microservices_order:latest
          imagePullPolicy: Always
          name: order
          ports:
            - containerPort: 8004
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s_deployment.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: order-db
  name: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o k8s_deployment.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/ecommerce-microservices-default: "true"
        io.kompose.service: order-db
    spec:
      containers:
        - args:
            - -p
            - "5436"
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: postgres_order
            - name: POSTGRES_PASSWORD
              value: mysecurepassword
            - name: POSTGRES_USER
              value: postgres
          image: postgres:latest
          name: order-db
          ports:
            - containerPort: 5436
              hostPort: 5437
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-order-db-data
      restartPolicy: Always
      volumes:
        - name: postgresql-order-db-data
          persistentVolumeClaim:
            claimName: postgresql-order-db-data
