apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s_deployment.yml
    kompose.image-pull-policy: Never
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: order
  name: order
spec:
  type: LoadBalancer
  ports:
    - name: "8005"
      port: 8005
      targetPort: 8004

  selector:
    io.kompose.service: order

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s_deployment.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: order-db
  name: order-db
spec:
  type: ClusterIP
  ports:
    - name: "5437"
      port: 5437
      targetPort: 5436

  selector:
    io.kompose.service: order-db
 